sudo: false

env:
  global:
    - CC_TEST_REPORTER_ID=25b36de723dc43e9f0b1e4071bbd16acccae3b34030cc3954368826e74c25fe8

language: node_js
services: mongodb

branches:
  only:
    - master

node_js:
  - 8
  - 6


before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script: npm run coverage

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
